#!/bin/bash

# Base image
CENTOS7_BASE="centos7:base"
CENTOS7_JAVA="centos7:java-version"
CENTOS7_JAVA_SSH="centos7:java-ssh"
CENTOS7_JON_AGENT="centos7:jon-agent"

# Products
DOMAIN_CONTROLLER_CONTAINER_NAME="eap-domain"
APACHE_CONTAINER_NAME="apache"
JON_SERVER_CONTAINER_NAME="jon-server"
JON_POSTGRES_CONTAINER_NAME="jon-postgres"
HOST_CONTAINER_NAME="eap-host"
STANDALONE_CONTAINER_NAME="eap-standalone"
MYSQL_CONTAINER_NAME="mysql-server"
POSTGRESQL_CONTAINER_NAME="postgresql-server"
FUSE_CONTAINER_NAME="fuse"
BPMS_CONTAINER_NAME="bpms"
BRMS_CONTAINER_NAME="brms"
JDG_CONTAINER_NAME="jdg"
JDV_CONTAINER_NAME="jdv"
KEYCLOAK_CONTAINER_NAME="keycloak-server"
KERBEROS_CONTAINER_NAME="kerberos"
DNSMASQ_CONTAINER_NAME="dnsmasq"
WILDFLY_CONTAINER_NAME="wildfly"

# Demos
DEMO_COOL_STORE="demo-cool-store"
DEMO_BUSINESS_RESOURCE_OPTIMIZER="demo-resource-optimizer"
DEMO_APACHE="demo-$APACHE_CONTAINER_NAME"
DEMO_EAP_DOMAIN="demo-$DOMAIN_CONTROLLER_CONTAINER_NAME"
DEMO_EAP_HOST="demo-$HOST_CONTAINER_NAME"

DOCKER_USER="luszczynski"